!obj:pylearn2.train.Train {
    dataset: &train !obj:faceDataset.faceDataset {
        which_set: 'train',
        positive_samples: "/data/lisatmp3/chassang/facedet/16/pos16_100_eq.npy",
        negative_samples: "/data/lisatmp3/chassang/facedet/16/neg16_100_eq.npy",
        axes: ['c', 0, 1, 'b']
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 128,
                layers: [
                 !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'h0',
                     num_channels: 32,
                     kernel_shape: [4, 4],
                     num_pieces: 1,
                     pool_shape: [2, 2],
                     pool_stride: [1, 1],
                     irange: .005,
                     max_kernel_norm: 7.9,
                     tied_b: 1
                 },
                 !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'h1',
                     num_channels: 64,
                     kernel_shape: [4, 4],
                     num_pieces: 1,
                     pool_shape: [2, 2],
                     pool_stride: [1, 1],
                     irange: .05,
                     max_kernel_norm: 7.9,
                     tied_b: 1
                 },
                 !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'h2',
                     num_channels: 64,
                     kernel_shape: [3, 3],
                     num_pieces: 1,
                     pool_shape: [2, 2],
                     pool_stride: [1, 1],
                     irange: .05,
                     max_kernel_norm: 7.9,
                     tied_b: 1
                 },
                 !obj:pylearn2.models.maxout.MaxoutConvC01B {
                     layer_name: 'wSo',
                     num_channels: 16,
                     # Kernel_shape must match the input_shape to send a 1*1 output
                     kernel_shape: [5,5],
                     num_pieces: 1,
                     pool_shape: [1,1],
                     pool_stride: [1,1],
                     irange: 0.01,
                     max_kernel_norm: 7.9,
                     tied_b: 1
                 },
                 !obj:pylearn2.models.mlp.WindowChannelLayer {
                     layer_name: 'winchan',
                     window: [0,2]
                 },
                 !obj:utils.layer.SoftmaxExtended.SoftmaxExtended {
                     max_col_norm: 1.9365,
                     layer_name: 'y',
                     n_classes: 2,
                     irange: .1,
                     thresholds: [0.3, 0.1, 0.2, 0.4]
                 }
                ],
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [16, 16],
            num_channels: 3,
            axes: ['c', 0, 1, 'b'],
        },
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .00001,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: 0.1,
        },
        train_iteration_mode: 'batchwise_shuffled_sequential',
        monitor_iteration_mode: 'even_sequential',
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:faceDataset.faceDataset {
                        which_set: 'valid',
                        positive_samples: "/data/lisatmp3/chassang/facedet/16/pos16_100_eq.npy",
                        negative_samples: "/data/lisatmp3/chassang/facedet/16/neg16_100_eq.npy",
                        axes: ['c', 0, 1, 'b'],
                      },
            },
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 1000,
            new_epochs: True
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
                channel_name: 'valid_y_misclass',
                save_path: "2layers_16_best_decay.pkl"
            }
    ],
    save_path: "2layers_16_decay.pkl",
    save_freq: 5
}
