!obj:pylearn2.train.Train {
    dataset: &train !obj:datasets.ellipseDataset.ellipseDataset {
        which_set: 'train',
        ratio: 0.9,
        feats: "/u/ballasn/project/facedet/facedet/utils/FDDB/bbox2ellipse/regression/fold_data/feats_fold1.npy",
        labels: "/u/ballasn/project/facedet/facedet/utils/FDDB/bbox2ellipse/regression/fold_data/labels_fold1.npy",
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 128,
                layers: [
                 !obj:pylearn2.models.mlp.Linear {
                     layer_name: 'W',
                     dim: 5,
                     irange: .005,
                     #max_kernel_norm: .9,
                 },
                ],
        input_space: !obj:pylearn2.space.VectorSpace {
            dim: 2050,
        },
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .00001,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum        {
            init_momentum: 0.1,
        },
        train_iteration_mode: 'batchwise_shuffled_sequential',
        monitor_iteration_mode: 'even_sequential',
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:datasets.ellipseDataset.ellipseDataset {
                        which_set: 'valid',
                        ratio: 0.9,
                        feats: "/u/ballasn/project/facedet/facedet/utils/FDDB/bbox2ellipse/regression/fold_data/feats_fold1.npy",
                        labels: "/u/ballasn/project/facedet/facedet/utils/FDDB/bbox2ellipse/regression/fold_data/labels_fold1.npy",
                      },
            },
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 1000,
            new_epochs: True
        },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
                channel_name: 'valid_objective',
                save_path: "./models/reg_best.pkl"
            }
    ],
    save_path: "./models/reg.pkl",
    save_freq: 5
}
